<?php

namespace Rdc\Cart\CartBusinessBundle\Repository;

use Rdc\Cart\CartBusinessBundle\Repository\BusinessRepository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends BusinessRepository
{
    public function getOrders()
    {
        return $this->findBy(['status'=>2, 'notified'=>false]);
    }

}
