NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api-doc

cart_api:
    resource: "@CartApiBundle/Controller/"
    type:     rest
    prefix:   /api


