Rdc\Cart\CartBusinessBundle\Entity\Address:
    properties:
        addressId:
            - NotBlank: ~
            - Type:
                type: integer
        firstname:
            - NotBlank: ~
            - Type:
                type: string
        lastname:
            - NotBlank: ~
            - Type:
                type: string
        address1:
            - NotBlank: ~
            - Type:
                type: string
        address2:
            - Type:
                type: string
        city:
            - NotBlank: ~
            - Type:
                type: string
        zip:
            - NotBlank: ~
            - Type:
                type: string
        countryCode:
            - NotBlank: ~
            - Type:
                type: string
            - Length:
                min: 2
                max: 2
        countryLabel:
            - NotBlank: ~
            - Type:
                type: string
        phone:
            - Type:
                type: string
        mobilePhone:
            - Type:
                type: string
        workPhone:
            - Type:
                type: string
        fax:
            - Type:
                type: string
        rcs:
            - Type:
                type: string
        accessCode:
            - Type:
                type: string