Rdc\Cart\CartBusinessBundle\Vo\Behavior:
    properties:
        source:
            - NotBlank: ~
            - Type:
                type: integer
        target:
            - NotBlank: ~
            - Type:
                type: array
        type:
            - NotBlank: ~
            - Choice: [shipping_address, billing_address, shipping_type]
            - Type:
                type: string

