Rdc\Cart\CartBusinessBundle\Entity\Cart:
    getters:
        address:
            - Valid: ~
        customer:
            - Valid: ~
        shipping:
            - Valid: ~
        payment:
            - Valid: ~
        items:
            - Valid: { traverse: true }
    properties:
        channel:
            - NotBlank: ~
            - Type:
                type: string
        shopId:
            - NotBlank: ~
            - Type:
                type: integer
        status:
            - NotBlank: ~
            - Type:
                type: string
        behaviors:
            - Type: array
