Rdc\Cart\CartBusinessBundle\Vo\Customer:
    properties:
        customerId:
            - NotBlank: ~
            - Type:
                type: integer
        firstname:
            - NotBlank: ~
            - Type:
                type: string
        lastname:
            - NotBlank: ~
            - Type:
                type: string
        email:
            - NotBlank: ~
            - Email: ~
            - Type:
                type: string
