Rdc\Cart\CartBusinessBundle\Vo\Item:
    properties:
        itemId:
            - NotBlank: ~
            - Type:
                type: integer
        quantity:
            - NotBlank: ~
            - Type:
                type: integer

