Rdc\Cart\CartBusinessBundle\Entity\Payment:
    properties:
        typeId:
            - NotBlank: ~
            - Type:
                type: integer
        typeName:
            - NotBlank: ~
            - Type:
                type: string

