Rdc\Cart\CartBusinessBundle\Vo\Shipping:
    properties:
        typeId:
            - NotBlank: ~
            - Type:
                type: integer
        typeName:
            - NotBlank: ~
            - Type:
                type: string
